// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjeEBaDDoMtE3qQkng0E0QZ_Nlke5bfcY',
    appId: '1:656657507951:web:33ae62598f64ab11768f9a',
    messagingSenderId: '656657507951',
    projectId: 'flutter-shopping-cart-d86fa',
    authDomain: 'flutter-shopping-cart-d86fa.firebaseapp.com',
    storageBucket: 'flutter-shopping-cart-d86fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWJMSukuz_9OjRcBeCPIQ8WJ4a2C2t9uA',
    appId: '1:656657507951:android:763d1e734677f989768f9a',
    messagingSenderId: '656657507951',
    projectId: 'flutter-shopping-cart-d86fa',
    storageBucket: 'flutter-shopping-cart-d86fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ4A3LMer82SjvJl2NAHLjLg3vXqjVK8Q',
    appId: '1:656657507951:ios:c453fe1d0b349b90768f9a',
    messagingSenderId: '656657507951',
    projectId: 'flutter-shopping-cart-d86fa',
    storageBucket: 'flutter-shopping-cart-d86fa.appspot.com',
    iosClientId: '656657507951-stte73im6rgsvbblaua68ve7785dji8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ4A3LMer82SjvJl2NAHLjLg3vXqjVK8Q',
    appId: '1:656657507951:ios:c453fe1d0b349b90768f9a',
    messagingSenderId: '656657507951',
    projectId: 'flutter-shopping-cart-d86fa',
    storageBucket: 'flutter-shopping-cart-d86fa.appspot.com',
    iosClientId: '656657507951-stte73im6rgsvbblaua68ve7785dji8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGetx',
  );
}
